version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - python docs/install_pyopenms.py
    
python:
  install:
    - requirements: docs/requirements.txt
