name: binder-env
channels:
  - conda-forge
  - bioconda
  - openms
dependencies:
  - python=3.10
  - pyopenms
  - matplotlib
  - plotly
  - pandas
  - adjustText
  - scikit-learn
  - requests
  - bokeh
  - datashader
  - holoviews
  - pyviz_comms
  - jupyter-server-proxy
  - pip
  - pip:
    - massql
