#!/bin/bash

wget https://nightly.link/OpenMS/OpenMS/workflows/pyopenms-wheels/nightly/Linux-wheels.zip\?status\=completed
mv Linux-wheels.zip\?status=completed Linux-wheels.zip
unzip Linux-wheels.zip
pip install pyopenms_nightly-*-cp37-cp37m-manylinux2014_x86_64.whl

# Enable nbserverproxy
#jupyter serverextension enable --sys-prefix jupyter_server_proxy

# Install the bokeh server extension so that Bokeh launches at startup
#mv .binder/bokehserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# Enable Bokeh extension
#jupyter serverextension enable --sys-prefix bokehserverextension

#jupyter labextension install @jupyterlab/server-proxy