name: reviewdog-flakehell
on: [push]
jobs:
  flakehell:
    name: runner / flakehell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: '3.10'
      - uses: sailingpalmtree/reviewdog-flakehell-action@v1.0
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning